sudo: required # to use docker you need su permission
services:
  - docker

before_install:
  - docker bild -t ooje/docker-react:v1 -f Dockerfile.dev .

script:
  - dokcer run ooje/docker-react:v1 npm run test -- --coveraged
