sudo: required # to use docker you need su permission
services:
  - docker

before_install:
  - docker build -t ooje/docker-react:v2 -f Dockerfile.dev .

script:
  - docker run -e CI=true ooje/docker-react:v2 npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-west-2"
  app: "docker-react"
  env: "docker-react-env"
  bucket_name: "elasticbeanstalk-eu-west-2-803138084742"
  bucket_path: "docker-react"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
