sudo: required # to use docker you need su permission
services:
  - docker

before_install:
  - docker build -t ooje/docker-react:v2 -f Dockerfile.dev .

script:
  - docker run ooje/docker-react:v2 npm run test -- --coverage
